packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  "@types/node": ^24
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@0.1.24
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.24
  vite-plus: 0.1.24
  "@electric-sql/pglite": ^0.5.3
  alchemy: 2.0.0-beta.57
  effect: 4.0.0-beta.84
  "@effect/platform-bun": 4.0.0-beta.84
  "@effect/platform-node": 4.0.0-beta.84
  tslib: ^2.8.1
  "@vitest/coverage-v8": 4.1.9
  shiki: ^4.2.0
  pkg-pr-new: ^0.0.75
  "@changesets/cli": ^2.31.0
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
    "@distilled.cloud/cloudflare": "*"
allowBuilds:
  esbuild: true
  "@parcel/watcher": true
  msgpackr-extract: true
  unrs-resolver: true
  workerd: true
minimumReleaseAgeExclude:
  - "@distilled.cloud/aws@0.26.1"
  - "@distilled.cloud/axiom@0.26.1"
  - "@distilled.cloud/cloudflare@0.26.1"
  - "@distilled.cloud/core@0.26.1"
  - "@distilled.cloud/neon@0.26.1"
  - "@distilled.cloud/planetscale@0.26.1"
  - alchemy@2.0.0-beta.57
  - '@prisma-next/adapter-postgres@0.16.0'
  - '@prisma-next/cli-telemetry@0.16.0'
  - '@prisma-next/cli@0.16.0'
  - '@prisma-next/config-loader@0.16.0'
  - '@prisma-next/config@0.16.0'
  - '@prisma-next/contract-authoring@0.16.0'
  - '@prisma-next/contract@0.16.0'
  - '@prisma-next/driver-postgres@0.16.0'
  - '@prisma-next/emitter@0.16.0'
  - '@prisma-next/errors@0.16.0'
  - '@prisma-next/extension-author-tools@0.16.0'
  - '@prisma-next/family-sql@0.16.0'
  - '@prisma-next/framework-components@0.16.0'
  - '@prisma-next/ids@0.16.0'
  - '@prisma-next/language-server@0.16.0'
  - '@prisma-next/migration-tools@0.16.0'
  - '@prisma-next/operations@0.16.0'
  - '@prisma-next/postgres@0.16.0'
  - '@prisma-next/psl-parser@0.16.0'
  - '@prisma-next/psl-printer@0.16.0'
  - '@prisma-next/sql-builder@0.16.0'
  - '@prisma-next/sql-contract-emitter@0.16.0'
  - '@prisma-next/sql-contract-psl@0.16.0'
  - '@prisma-next/sql-contract-ts@0.16.0'
  - '@prisma-next/sql-contract@0.16.0'
  - '@prisma-next/sql-errors@0.16.0'
  - '@prisma-next/sql-operations@0.16.0'
  - '@prisma-next/sql-orm-client@0.16.0'
  - '@prisma-next/sql-relational-core@0.16.0'
  - '@prisma-next/sql-runtime@0.16.0'
  - '@prisma-next/sql-schema-ir@0.16.0'
  - '@prisma-next/target-postgres@0.16.0'
  - '@prisma-next/ts-render@0.16.0'
  - '@prisma-next/utils@0.16.0'
