// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma-next/adapter-postgres/operation-types';
import type {
  CodecTypes as PostgisTypes,
  Geometry,
} from '@prisma-next/extension-postgis/codec-types';
import type { QueryOperationTypes as PostgisQueryOperationTypes } from '@prisma-next/extension-postgis/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  Timestamp,
  Timestamptz,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma-next/target-postgres/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma-next/sql-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'sha256:6c2de2dd04e4425aa3a8ba8e05df0c812204ef610bb975ae1b2b7d19c74fbdb2'>;
export type ExecutionHash =
  ExecutionHashBase<'sha256:54edb84b4449d91a93a26316d3fdfdf0dc37e4a07930e362682ddd1745d357b5'>;
export type ProfileHash =
  ProfileHashBase<'sha256:9c8aa3114e84ed3b7ea2bd57526d9c2e1bf7c5292be694e9d3801f566fda7ccb'>;

export type CodecTypes = PgTypes & PostgisTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes> &
  PostgisQueryOperationTypes<CodecTypes>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Cafe: {
      readonly id: Char<36>;
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly location: Geometry<4326>;
    };
    readonly Neighborhood: {
      readonly id: Char<36>;
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly boundary: Geometry<4326>;
    };
    readonly Route: {
      readonly id: Char<36>;
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly path: Geometry<4326>;
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Cafe: {
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly location: CodecTypes['pg/geometry@1']['input'];
    };
    readonly Neighborhood: {
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly boundary: CodecTypes['pg/geometry@1']['input'];
    };
    readonly Route: {
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly path: CodecTypes['pg/geometry@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly cafe: {
      readonly id: Char<36>;
      readonly location: Geometry<4326>;
      readonly name: CodecTypes['pg/text@1']['output'];
    };
    readonly neighborhood: {
      readonly boundary: Geometry<4326>;
      readonly id: Char<36>;
      readonly name: CodecTypes['pg/text@1']['output'];
    };
    readonly route: {
      readonly id: Char<36>;
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly path: Geometry<4326>;
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly cafe: {
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly location: CodecTypes['pg/geometry@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
    };
    readonly neighborhood: {
      readonly boundary: CodecTypes['pg/geometry@1']['input'];
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
    };
    readonly route: {
      readonly id: CodecTypes['sql/char@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly path: CodecTypes['pg/geometry@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly cafe: {
              columns: {
                readonly id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly location: {
                  readonly nativeType: 'geometry';
                  readonly codecId: 'pg/geometry@1';
                  readonly nullable: false;
                  readonly typeRef: 'WgsGeometry';
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly neighborhood: {
              columns: {
                readonly id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly boundary: {
                  readonly nativeType: 'geometry';
                  readonly codecId: 'pg/geometry@1';
                  readonly nullable: false;
                  readonly typeRef: 'WgsGeometry';
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly route: {
              columns: {
                readonly id: {
                  readonly nativeType: 'character';
                  readonly codecId: 'sql/char@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 36 };
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly path: {
                  readonly nativeType: 'geometry';
                  readonly codecId: 'pg/geometry@1';
                  readonly nullable: false;
                  readonly typeRef: 'WgsGeometry';
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly types: {
      readonly WgsGeometry: {
        readonly kind: 'codec-instance';
        readonly codecId: 'pg/geometry@1';
        readonly nativeType: 'geometry';
        readonly typeParams: { readonly srid: 4326 };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly cafe: { readonly namespace: 'public' & NamespaceId; readonly model: 'Cafe' };
    readonly route: { readonly namespace: 'public' & NamespaceId; readonly model: 'Route' };
    readonly neighborhood: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Neighborhood';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Cafe: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly location: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/geometry@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'cafe';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly location: { readonly column: 'location' };
              };
            };
          };
          readonly Neighborhood: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly boundary: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/geometry@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'neighborhood';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly boundary: { readonly column: 'boundary' };
              };
            };
          };
          readonly Route: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly path: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/geometry@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'route';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly path: { readonly column: 'path' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly 'postgis.geometry': true;
      readonly returning: true;
    };
    readonly sql: {
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensionPacks: {
    readonly postgis: {
      readonly capabilities: { readonly postgres: { readonly 'postgis.geometry': true } };
      readonly familyId: 'sql';
      readonly id: 'postgis';
      readonly kind: 'extension';
      readonly targetId: 'postgres';
      readonly types: {
        readonly codecTypes: {
          readonly import: {
            readonly alias: 'PostgisTypes';
            readonly named: 'CodecTypes';
            readonly package: '@prisma-next/extension-postgis/codec-types';
          };
          readonly typeImports: readonly [
            {
              readonly alias: 'Geometry';
              readonly named: 'Geometry';
              readonly package: '@prisma-next/extension-postgis/codec-types';
            },
          ];
        };
        readonly queryOperationTypes: {
          readonly import: {
            readonly alias: 'PostgisQueryOperationTypes';
            readonly named: 'QueryOperationTypes';
            readonly package: '@prisma-next/extension-postgis/operation-types';
          };
        };
        readonly storage: readonly [
          {
            readonly familyId: 'sql';
            readonly nativeType: 'geometry';
            readonly targetId: 'postgres';
            readonly typeId: 'pg/geometry@1';
          },
        ];
      };
      readonly version: '0.0.1';
    };
  };
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'cafe';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'neighborhood';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'route';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
