// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { CodecTypes as PgTypes } from "@prisma/orm-postgres/target/codec-types";
import type { QueryOperationTypes as PgTargetQueryOps } from "@prisma/orm-postgres/target/operation-types";
import type { CodecTypes as LtreeTypes, Ltree } from "prisma-ltree/codec-types";
import type { QueryOperationTypes as LtreeQueryOperationTypes } from "prisma-ltree/operation-types";

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from "@prisma/orm-postgres/family-contract/types";
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from "@prisma/orm-postgres/contract/types";

export type StorageHash =
  StorageHashBase<"fae0c94c760d88923664ac8fd0fb3730bc6402f7703718c8daa707b2f123b788">;
export type ExecutionHash =
  ExecutionHashBase<"21ae50faa9b7f351acd36d70398e24ff6d5c92eb08cfda85753524a43fa74f75">;
export type ProfileHash =
  ProfileHashBase<"3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2">;

export type CodecTypes = PgTypes & LtreeTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgTargetQueryOps<CodecTypes> &
  LtreeQueryOperationTypes<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly "pg/float@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/float4@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/float8@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/int@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/int2@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/int4@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/int8@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/int8number@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/interval@1": { readonly output: "pg/interval@1"; readonly nullable: true };
      readonly "pg/numeric@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/time-string@1": { readonly output: "pg/interval@1"; readonly nullable: true };
      readonly "pg/time-temporal@1": { readonly output: "pg/interval@1"; readonly nullable: true };
      readonly "pg/unboundedint@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "sql/float@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "sql/int@1": { readonly output: "pg/float8@1"; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly "pg/int@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/int2@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/int4@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/int8@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/int8number@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/numeric@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/unboundedint@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "sql/int@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: "pg/int8number@1"; readonly nullable: false };
    readonly anyInput: { readonly output: "pg/int8number@1"; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: "pg/int8@1"; readonly nullable: false };
    readonly anyInput: { readonly output: "pg/int8@1"; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly "pg/char@1": { readonly output: "pg/char@1"; readonly nullable: true };
      readonly "pg/date-string@1": { readonly output: "pg/date-string@1"; readonly nullable: true };
      readonly "pg/date-temporal@1": {
        readonly output: "pg/date-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/enum@1": { readonly output: "pg/enum@1"; readonly nullable: true };
      readonly "pg/float@1": { readonly output: "pg/float@1"; readonly nullable: true };
      readonly "pg/float4@1": { readonly output: "pg/float4@1"; readonly nullable: true };
      readonly "pg/float8@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/inet@1": { readonly output: "pg/inet@1"; readonly nullable: true };
      readonly "pg/int@1": { readonly output: "pg/int@1"; readonly nullable: true };
      readonly "pg/int2@1": { readonly output: "pg/int2@1"; readonly nullable: true };
      readonly "pg/int4@1": { readonly output: "pg/int4@1"; readonly nullable: true };
      readonly "pg/int8@1": { readonly output: "pg/int8@1"; readonly nullable: true };
      readonly "pg/int8number@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
      readonly "pg/interval@1": { readonly output: "pg/interval@1"; readonly nullable: true };
      readonly "pg/numeric@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/text-array@1": { readonly output: "pg/text-array@1"; readonly nullable: true };
      readonly "pg/text@1": { readonly output: "pg/text@1"; readonly nullable: true };
      readonly "pg/time-string@1": { readonly output: "pg/time-string@1"; readonly nullable: true };
      readonly "pg/time-temporal@1": {
        readonly output: "pg/time-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-string@1": {
        readonly output: "pg/timestamp-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-temporal@1": {
        readonly output: "pg/timestamp-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-date@1": {
        readonly output: "pg/timestamptz-date@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-string@1": {
        readonly output: "pg/timestamptz-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-temporal@1": {
        readonly output: "pg/timestamptz-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timetz@1": { readonly output: "pg/timetz@1"; readonly nullable: true };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "pg/varchar@1": { readonly output: "pg/text@1"; readonly nullable: true };
      readonly "sql/char@1": { readonly output: "sql/char@1"; readonly nullable: true };
      readonly "sql/float@1": { readonly output: "sql/float@1"; readonly nullable: true };
      readonly "sql/int@1": { readonly output: "sql/int@1"; readonly nullable: true };
      readonly "sql/text@1": { readonly output: "sql/text@1"; readonly nullable: true };
      readonly "sql/varchar@1": { readonly output: "pg/text@1"; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly "pg/char@1": { readonly output: "pg/char@1"; readonly nullable: true };
      readonly "pg/date-string@1": { readonly output: "pg/date-string@1"; readonly nullable: true };
      readonly "pg/date-temporal@1": {
        readonly output: "pg/date-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/enum@1": { readonly output: "pg/enum@1"; readonly nullable: true };
      readonly "pg/float@1": { readonly output: "pg/float@1"; readonly nullable: true };
      readonly "pg/float4@1": { readonly output: "pg/float4@1"; readonly nullable: true };
      readonly "pg/float8@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/inet@1": { readonly output: "pg/inet@1"; readonly nullable: true };
      readonly "pg/int@1": { readonly output: "pg/int@1"; readonly nullable: true };
      readonly "pg/int2@1": { readonly output: "pg/int2@1"; readonly nullable: true };
      readonly "pg/int4@1": { readonly output: "pg/int4@1"; readonly nullable: true };
      readonly "pg/int8@1": { readonly output: "pg/int8@1"; readonly nullable: true };
      readonly "pg/int8number@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
      readonly "pg/interval@1": { readonly output: "pg/interval@1"; readonly nullable: true };
      readonly "pg/numeric@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/text-array@1": { readonly output: "pg/text-array@1"; readonly nullable: true };
      readonly "pg/text@1": { readonly output: "pg/text@1"; readonly nullable: true };
      readonly "pg/time-string@1": { readonly output: "pg/time-string@1"; readonly nullable: true };
      readonly "pg/time-temporal@1": {
        readonly output: "pg/time-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-string@1": {
        readonly output: "pg/timestamp-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-temporal@1": {
        readonly output: "pg/timestamp-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-date@1": {
        readonly output: "pg/timestamptz-date@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-string@1": {
        readonly output: "pg/timestamptz-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-temporal@1": {
        readonly output: "pg/timestamptz-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timetz@1": { readonly output: "pg/timetz@1"; readonly nullable: true };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "pg/varchar@1": { readonly output: "pg/text@1"; readonly nullable: true };
      readonly "sql/char@1": { readonly output: "sql/char@1"; readonly nullable: true };
      readonly "sql/float@1": { readonly output: "sql/float@1"; readonly nullable: true };
      readonly "sql/int@1": { readonly output: "sql/int@1"; readonly nullable: true };
      readonly "sql/text@1": { readonly output: "sql/text@1"; readonly nullable: true };
      readonly "sql/varchar@1": { readonly output: "pg/text@1"; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly "pg/float@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/float4@1": { readonly output: "pg/float4@1"; readonly nullable: true };
      readonly "pg/float8@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "pg/int@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
      readonly "pg/int2@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
      readonly "pg/int4@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
      readonly "pg/int8@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
      readonly "pg/int8number@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
      readonly "pg/interval@1": { readonly output: "pg/interval@1"; readonly nullable: true };
      readonly "pg/numeric@1": { readonly output: "pg/numeric@1"; readonly nullable: true };
      readonly "pg/time-string@1": { readonly output: "pg/interval@1"; readonly nullable: true };
      readonly "pg/time-temporal@1": { readonly output: "pg/interval@1"; readonly nullable: true };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "sql/float@1": { readonly output: "pg/float8@1"; readonly nullable: true };
      readonly "sql/int@1": { readonly output: "pg/int8number@1"; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly "pg/int@1": { readonly output: "pg/int8@1"; readonly nullable: true };
      readonly "pg/int2@1": { readonly output: "pg/int8@1"; readonly nullable: true };
      readonly "pg/int4@1": { readonly output: "pg/int8@1"; readonly nullable: true };
      readonly "pg/int8@1": { readonly output: "pg/unboundedint@1"; readonly nullable: true };
      readonly "pg/int8number@1": { readonly output: "pg/unboundedint@1"; readonly nullable: true };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": { readonly output: "pg/int8@1"; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]["json"]
    ? Encoded
    : CodecTypes[CodecId]["json"]
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Taxon: {
      readonly commonName: CodecTypes["pg/text@1"]["output"] | null;
      readonly extinct: CodecTypes["pg/bool@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly maExtinct: CodecTypes["pg/float8@1"]["output"] | null;
      readonly maOrigin: CodecTypes["pg/float8@1"]["output"] | null;
      readonly path: CodecTypes["pg/ltree@1"]["output"];
      readonly rank: CodecTypes["pg/text@1"]["output"];
      readonly scientificName: CodecTypes["pg/text@1"]["output"];
      readonly thumbnailUrl: CodecTypes["pg/text@1"]["output"] | null;
      readonly wikiUrl: CodecTypes["pg/text@1"]["output"];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Taxon: {
      readonly commonName: CodecTypes["pg/text@1"]["input"] | null;
      readonly extinct: CodecTypes["pg/bool@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly maExtinct: CodecTypes["pg/float8@1"]["input"] | null;
      readonly maOrigin: CodecTypes["pg/float8@1"]["input"] | null;
      readonly path: CodecTypes["pg/ltree@1"]["input"];
      readonly rank: CodecTypes["pg/text@1"]["input"];
      readonly scientificName: CodecTypes["pg/text@1"]["input"];
      readonly thumbnailUrl: CodecTypes["pg/text@1"]["input"] | null;
      readonly wikiUrl: CodecTypes["pg/text@1"]["input"];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly taxon: {
      readonly common_name: CodecTypes["pg/text@1"]["output"] | null;
      readonly extinct: CodecTypes["pg/bool@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly ma_extinct: CodecTypes["pg/float8@1"]["output"] | null;
      readonly ma_origin: CodecTypes["pg/float8@1"]["output"] | null;
      readonly path: CodecTypes["pg/ltree@1"]["output"];
      readonly rank: CodecTypes["pg/text@1"]["output"];
      readonly scientific_name: CodecTypes["pg/text@1"]["output"];
      readonly thumbnail_url: CodecTypes["pg/text@1"]["output"] | null;
      readonly wiki_url: CodecTypes["pg/text@1"]["output"];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly taxon: {
      readonly common_name: CodecTypes["pg/text@1"]["input"] | null;
      readonly extinct: CodecTypes["pg/bool@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly ma_extinct: CodecTypes["pg/float8@1"]["input"] | null;
      readonly ma_origin: CodecTypes["pg/float8@1"]["input"] | null;
      readonly path: CodecTypes["pg/ltree@1"]["input"];
      readonly rank: CodecTypes["pg/text@1"]["input"];
      readonly scientific_name: CodecTypes["pg/text@1"]["input"];
      readonly thumbnail_url: CodecTypes["pg/text@1"]["input"] | null;
      readonly wiki_url: CodecTypes["pg/text@1"]["input"];
    };
  };
};

export namespace Models {
  export type public_Taxon = {
    commonName: CodecTypes["pg/text@1"]["output"] | null;
    extinct: CodecTypes["pg/bool@1"]["output"];
    id: CodecTypes["pg/text@1"]["output"];
    maExtinct: CodecTypes["pg/float8@1"]["output"] | null;
    maOrigin: CodecTypes["pg/float8@1"]["output"] | null;
    path: CodecTypes["pg/ltree@1"]["output"];
    rank: CodecTypes["pg/text@1"]["output"];
    scientificName: CodecTypes["pg/text@1"]["output"];
    thumbnailUrl: CodecTypes["pg/text@1"]["output"] | null;
    wikiUrl: CodecTypes["pg/text@1"]["output"];
    readonly [RelationKeys]?: never;
  };
}

export declare const models: {
  public: {
    Taxon: Models.public_Taxon;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: "public";
        readonly kind: "postgres-schema";
        readonly entries: {
          readonly table: {
            readonly taxon: {
              columns: {
                readonly common_name: {
                  readonly dataType: "pg/text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly extinct: {
                  readonly dataType: "pg/bool";
                  readonly codecId: "pg/bool@1";
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly id: {
                  readonly dataType: "pg/text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly ma_extinct: {
                  readonly dataType: "pg/float8";
                  readonly codecId: "pg/float8@1";
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly ma_origin: {
                  readonly dataType: "pg/float8";
                  readonly codecId: "pg/float8@1";
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly path: {
                  readonly dataType: "ltree/ltree";
                  readonly codecId: "pg/ltree@1";
                  readonly nullable: false;
                  readonly typeRef: "Path";
                  readonly many: false;
                };
                readonly rank: {
                  readonly dataType: "pg/text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly scientific_name: {
                  readonly dataType: "pg/text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                  readonly many: false;
                };
                readonly thumbnail_url: {
                  readonly dataType: "pg/text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                  readonly many: false;
                };
                readonly wiki_url: {
                  readonly dataType: "pg/text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                  readonly many: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [{ readonly columns: readonly ["path"] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly types: {
      readonly Path: {
        readonly kind: "codec-instance";
        readonly codecId: "pg/ltree@1";
        readonly dataType: "ltree/ltree";
        readonly typeParams: Record<string, never>;
      };
    };
    readonly storageHash: StorageHash;
  }>,
  "roots" | "domain"
> & {
  readonly target: "postgres";
  readonly targetFamily: "sql";
  readonly roots: {
    readonly taxon: { readonly namespace: "public" & NamespaceId; readonly model: "Taxon" };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Taxon: {
            readonly fields: {
              readonly commonName: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly extinct: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/bool@1" };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly maExtinct: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/float8@1" };
              };
              readonly maOrigin: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/float8@1" };
              };
              readonly path: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/ltree@1" };
              };
              readonly rank: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly scientificName: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly thumbnailUrl: {
                readonly nullable: true;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
              readonly wikiUrl: {
                readonly nullable: false;
                readonly type: { readonly kind: "scalar"; readonly codecId: "pg/text@1" };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: "taxon";
              readonly namespaceId: "public";
              readonly fields: {
                readonly commonName: { readonly column: "common_name" };
                readonly extinct: { readonly column: "extinct" };
                readonly id: { readonly column: "id" };
                readonly maExtinct: { readonly column: "ma_extinct" };
                readonly maOrigin: { readonly column: "ma_origin" };
                readonly path: { readonly column: "path" };
                readonly rank: { readonly column: "rank" };
                readonly scientificName: { readonly column: "scientific_name" };
                readonly thumbnailUrl: { readonly column: "thumbnail_url" };
                readonly wikiUrl: { readonly column: "wiki_url" };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly forKeyShare: true;
      readonly forNoKeyUpdate: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly "ltree.path": true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly forShare: true;
      readonly forUpdate: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly lateral: true;
      readonly lockNowait: true;
      readonly lockOf: true;
      readonly lockSkipLocked: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {
    readonly ltree: {
      readonly capabilities: { readonly postgres: { readonly "ltree.path": true } };
      readonly familyId: "sql";
      readonly id: "ltree";
      readonly kind: "extension";
      readonly targetId: "postgres";
      readonly types: {
        readonly codecTypes: {
          readonly import: {
            readonly alias: "LtreeTypes";
            readonly named: "CodecTypes";
            readonly package: "prisma-ltree/codec-types";
          };
          readonly typeImports: readonly [
            {
              readonly alias: "Ltree";
              readonly named: "Ltree";
              readonly package: "prisma-ltree/codec-types";
            },
          ];
        };
        readonly queryOperationTypes: {
          readonly import: {
            readonly alias: "LtreeQueryOperationTypes";
            readonly named: "QueryOperationTypes";
            readonly package: "prisma-ltree/operation-types";
          };
        };
      };
      readonly version: "0.1.0";
    };
  };
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly onCreate: { readonly id: "uuidv4"; readonly kind: "generator" };
          readonly ref: {
            readonly entry: "taxon";
            readonly field: "id";
            readonly namespace: "public";
          };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract["storage"]["namespaces"];
