name: CI

on:
  push:
    branches: ["main"]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: "24"
          cache: true
          run-install: |
            args: ['--frozen-lockfile']

      - name: Validate extension
        run: |
          cd packages/extension-ltree
          vp run check-pins
          vp run build
          vp check
          vp test

      - name: Publish preview package
        if: ${{ github.event_name == 'pull_request' }}
        run: vp exec pkg-pr-new publish './packages/extension-ltree' --commentWithSha --packageManager=pnpm
